# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4hQDR9eN9qQZ1fEBKH5r6qbYXihGfAE
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression





df=pd.read_csv('/content/hedhi hya.csv')

df.head()

df.tail()

df["Years of Experience"].count()

df["Years of Experience"].unique()

df["Years of Experience"].dropna()

df["Years of Experience"].replace("*",df["Years of Experience"].mean())

!pip install ydata_profiling

from ydata_profiling import ProfileReport

ProfileReport(df)

df.dropna(inplace=True)

df["Years of Experience"].fillna(df["Years of Experience"].mean(),inplace=True)

df["Years of Experience"].drop_duplicates(inplace=True)

df.info()

X=df["Years of Experience"]
Y=df["Salary (USD)"]

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

model=LinearRegression()

model.fit(X_train.values.reshape(-1,1),Y_train)

a=model.predict([[1]])
a

years=int(input("donner years"))
print(model.predict([[years]]))